name: yukan_app_ukk
description: "Aplikasi kantin sekolah menggunakan API yang sudah disediakan"

publish_to: 'none'

version: 0.1.0-b

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For changing the app icon easily
# run command: 'dart run flutter_launcher_icons'
flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          style: normal
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
#        - asset: assets/fonts/GoogleSans-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
#          style: italic
#          weight: 700
